/**
 * Complete game database with all content
 * Includes enemies, items, abilities, quests, NPCs, and more
 */

import {
  Ability,
  Achievement,
  AbilityType,
  AchievementType,
  CharacterClass,
  ClassTemplate,
  CraftingRecipe,
  DamageType,
  Enemy,
  EquipmentSlot,
  Item,
  ItemType,
  NPC,
  Quest,
  QuestObjectiveType,
  QuestStatus,
  Skill,
  StatusEffect,
} from "./game-types";

// ============================================================================
// CLASS TEMPLATES
// ============================================================================

export const classTemplates: Record<CharacterClass, ClassTemplate> = {
  [CharacterClass.WARRIOR]: {
    class: CharacterClass.WARRIOR,
    baseStats: {
      maxHealth: 150,
      health: 150,
      maxMana: 30,
      mana: 30,
      strength: 18,
      intelligence: 10,
      dexterity: 12,
      constitution: 16,
      wisdom: 11,
      charisma: 10,
      armor: 15,
      magicResist: 5,
      critChance: 0.1,
      critDamage: 1.5,
      attackSpeed: 1.0,
      castSpeed: 0.8,
    },
    startingAbilities: ["slash", "shield_bash", "power_strike"],
    description: "Strong melee fighter with high HP and armor",
    color: "#DC2626",
  },
  [CharacterClass.MAGE]: {
    class: CharacterClass.MAGE,
    baseStats: {
      maxHealth: 80,
      health: 80,
      maxMana: 150,
      mana: 150,
      strength: 8,
      intelligence: 18,
      dexterity: 12,
      constitution: 10,
      wisdom: 14,
      charisma: 12,
      armor: 5,
      magicResist: 20,
      critChance: 0.15,
      critDamage: 2.0,
      attackSpeed: 0.8,
      castSpeed: 1.2,
    },
    startingAbilities: ["fireball", "ice_bolt", "mana_shield"],
    description: "Powerful spellcaster with high mana and magic damage",
    color: "#3B82F6",
  },
  [CharacterClass.ROGUE]: {
    class: CharacterClass.ROGUE,
    baseStats: {
      maxHealth: 100,
      health: 100,
      maxMana: 60,
      mana: 60,
      strength: 12,
      intelligence: 12,
      dexterity: 18,
      constitution: 11,
      wisdom: 10,
      charisma: 13,
      armor: 8,
      magicResist: 8,
      critChance: 0.25,
      critDamage: 2.5,
      attackSpeed: 1.3,
      castSpeed: 1.0,
    },
    startingAbilities: ["backstab", "shadow_strike", "evasion"],
    description: "Agile fighter with high critical strike chance",
    color: "#8B5CF6",
  },
  [CharacterClass.PALADIN]: {
    class: CharacterClass.PALADIN,
    baseStats: {
      maxHealth: 130,
      health: 130,
      maxMana: 100,
      mana: 100,
      strength: 15,
      intelligence: 12,
      dexterity: 11,
      constitution: 14,
      wisdom: 15,
      charisma: 14,
      armor: 12,
      magicResist: 15,
      critChance: 0.12,
      critDamage: 1.8,
      attackSpeed: 0.95,
      castSpeed: 1.0,
    },
    startingAbilities: ["holy_strike", "divine_shield", "heal"],
    description: "Balanced fighter with healing and protection abilities",
    color: "#F59E0B",
  },
};

// ============================================================================
// ABILITIES
// ============================================================================

export const abilities: Record<string, Ability> = {
  slash: {
    id: "slash",
    name: "Slash",
    description: "Basic melee attack",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.PHYSICAL,
    baseDamage: 15,
    manaCost: 0,
    cooldown: 0,
    range: 1,
    targetCount: 1,
    scalingStats: [{ stat: "strength", multiplier: 1.2 }],
    icon: "⚔️",
    animation: "slash",
    sound: "slash",
    levelRequired: 1,
    classRequired: CharacterClass.WARRIOR,
  },
  shield_bash: {
    id: "shield_bash",
    name: "Shield Bash",
    description: "Stun enemy and deal damage",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.PHYSICAL,
    baseDamage: 20,
    manaCost: 10,
    cooldown: 3,
    range: 1,
    targetCount: 1,
    statusEffects: [{ effect: StatusEffect.STUN, chance: 0.6, duration: 2 }],
    scalingStats: [{ stat: "strength", multiplier: 1.0 }],
    icon: "🛡️",
    animation: "bash",
    sound: "bash",
    levelRequired: 3,
    classRequired: CharacterClass.WARRIOR,
  },
  power_strike: {
    id: "power_strike",
    name: "Power Strike",
    description: "Powerful attack with high damage",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.PHYSICAL,
    baseDamage: 35,
    manaCost: 20,
    cooldown: 5,
    range: 1,
    targetCount: 1,
    scalingStats: [{ stat: "strength", multiplier: 1.5 }],
    icon: "💥",
    animation: "power_strike",
    sound: "power_strike",
    levelRequired: 5,
    classRequired: CharacterClass.WARRIOR,
  },
  fireball: {
    id: "fireball",
    name: "Fireball",
    description: "Explosive fire damage to all enemies",
    type: AbilityType.MAGICAL,
    damageType: DamageType.FIRE,
    baseDamage: 25,
    manaCost: 30,
    cooldown: 4,
    range: 5,
    targetCount: -1,
    statusEffects: [{ effect: StatusEffect.BURN, chance: 0.5, duration: 3 }],
    scalingStats: [{ stat: "intelligence", multiplier: 1.3 }],
    icon: "🔥",
    animation: "fireball",
    sound: "fireball",
    levelRequired: 1,
    classRequired: CharacterClass.MAGE,
  },
  ice_bolt: {
    id: "ice_bolt",
    name: "Ice Bolt",
    description: "Freeze enemy in place",
    type: AbilityType.MAGICAL,
    damageType: DamageType.ICE,
    baseDamage: 20,
    manaCost: 25,
    cooldown: 3,
    range: 5,
    targetCount: 1,
    statusEffects: [{ effect: StatusEffect.FREEZE, chance: 0.7, duration: 2 }],
    scalingStats: [{ stat: "intelligence", multiplier: 1.2 }],
    icon: "❄️",
    animation: "ice_bolt",
    sound: "ice_bolt",
    levelRequired: 3,
    classRequired: CharacterClass.MAGE,
  },
  mana_shield: {
    id: "mana_shield",
    name: "Mana Shield",
    description: "Protect with magical barrier",
    type: AbilityType.BUFF,
    damageType: DamageType.FIRE,
    baseDamage: 0,
    manaCost: 40,
    cooldown: 6,
    range: 1,
    targetCount: 1,
    statusEffects: [{ effect: StatusEffect.SHIELD, chance: 1.0, duration: 4 }],
    scalingStats: [{ stat: "intelligence", multiplier: 1.0 }],
    icon: "🛡️",
    animation: "mana_shield",
    sound: "shield",
    levelRequired: 5,
    classRequired: CharacterClass.MAGE,
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    description: "High critical strike damage",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.PHYSICAL,
    baseDamage: 25,
    manaCost: 15,
    cooldown: 3,
    range: 1,
    targetCount: 1,
    scalingStats: [{ stat: "dexterity", multiplier: 1.4 }],
    icon: "🗡️",
    animation: "backstab",
    sound: "backstab",
    levelRequired: 1,
    classRequired: CharacterClass.ROGUE,
  },
  shadow_strike: {
    id: "shadow_strike",
    name: "Shadow Strike",
    description: "Quick attack with poison",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.DARK,
    baseDamage: 20,
    manaCost: 20,
    cooldown: 4,
    range: 1,
    targetCount: 1,
    statusEffects: [{ effect: StatusEffect.POISON, chance: 0.6, duration: 4 }],
    scalingStats: [{ stat: "dexterity", multiplier: 1.3 }],
    icon: "🌑",
    animation: "shadow_strike",
    sound: "shadow_strike",
    levelRequired: 3,
    classRequired: CharacterClass.ROGUE,
  },
  evasion: {
    id: "evasion",
    name: "Evasion",
    description: "Dodge incoming attacks",
    type: AbilityType.BUFF,
    damageType: DamageType.PHYSICAL,
    baseDamage: 0,
    manaCost: 10,
    cooldown: 5,
    range: 1,
    targetCount: 1,
    scalingStats: [{ stat: "dexterity", multiplier: 1.0 }],
    icon: "💨",
    animation: "evasion",
    sound: "evasion",
    levelRequired: 5,
    classRequired: CharacterClass.ROGUE,
  },
  holy_strike: {
    id: "holy_strike",
    name: "Holy Strike",
    description: "Divine damage attack",
    type: AbilityType.PHYSICAL,
    damageType: DamageType.HOLY,
    baseDamage: 22,
    manaCost: 15,
    cooldown: 3,
    range: 1,
    targetCount: 1,
    scalingStats: [{ stat: "strength", multiplier: 1.1 }, { stat: "wisdom", multiplier: 0.5 }],
    icon: "✨",
    animation: "holy_strike",
    sound: "holy_strike",
    levelRequired: 1,
    classRequired: CharacterClass.PALADIN,
  },
  divine_shield: {
    id: "divine_shield",
    name: "Divine Shield",
    description: "Protect yourself and allies",
    type: AbilityType.BUFF,
    damageType: DamageType.HOLY,
    baseDamage: 0,
    manaCost: 35,
    cooldown: 5,
    range: 3,
    targetCount: -1,
    statusEffects: [{ effect: StatusEffect.SHIELD, chance: 1.0, duration: 3 }],
    scalingStats: [{ stat: "wisdom", multiplier: 1.0 }],
    icon: "⛪",
    animation: "divine_shield",
    sound: "shield",
    levelRequired: 3,
    classRequired: CharacterClass.PALADIN,
  },
  heal: {
    id: "heal",
    name: "Heal",
    description: "Restore health",
    type: AbilityType.HEALING,
    damageType: DamageType.HOLY,
    baseDamage: 0,
    manaCost: 30,
    cooldown: 4,
    range: 3,
    targetCount: 1,
    scalingStats: [{ stat: "wisdom", multiplier: 1.5 }],
    icon: "💚",
    animation: "heal",
    sound: "heal",
    levelRequired: 5,
    classRequired: CharacterClass.PALADIN,
  },
};

// ============================================================================
// ITEMS
// ============================================================================

export const items: Record<string, Item> = {
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    description: "A basic iron sword",
    type: ItemType.WEAPON,
    rarity: "common",
    icon: "⚔️",
    value: 50,
    weight: 2.5,
    equipmentSlot: EquipmentSlot.MAIN_HAND,
    stats: { strength: 3 },
  },
  steel_sword: {
    id: "steel_sword",
    name: "Steel Sword",
    description: "A well-crafted steel sword",
    type: ItemType.WEAPON,
    rarity: "uncommon",
    icon: "⚔️",
    value: 150,
    weight: 2.8,
    equipmentSlot: EquipmentSlot.MAIN_HAND,
    stats: { strength: 6 },
  },
  leather_armor: {
    id: "leather_armor",
    name: "Leather Armor",
    description: "Basic leather protection",
    type: ItemType.ARMOR,
    rarity: "common",
    icon: "🧥",
    value: 40,
    weight: 3.0,
    equipmentSlot: EquipmentSlot.CHEST,
    stats: { armor: 5 },
  },
  iron_plate: {
    id: "iron_plate",
    name: "Iron Plate Armor",
    description: "Heavy iron armor",
    type: ItemType.ARMOR,
    rarity: "uncommon",
    icon: "🛡️",
    value: 120,
    weight: 5.0,
    equipmentSlot: EquipmentSlot.CHEST,
    stats: { armor: 10 },
  },
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    description: "Restore 50 health",
    type: ItemType.CONSUMABLE,
    rarity: "common",
    icon: "🧪",
    value: 20,
    weight: 0.5,
    effects: [{ type: "healing", value: 50 }],
  },
  mana_potion: {
    id: "mana_potion",
    name: "Mana Potion",
    description: "Restore 50 mana",
    type: ItemType.CONSUMABLE,
    rarity: "common",
    icon: "🧪",
    value: 20,
    weight: 0.5,
    effects: [{ type: "healing", value: 50 }],
  },
  iron_ore: {
    id: "iron_ore",
    name: "Iron Ore",
    description: "Raw iron ore",
    type: ItemType.MATERIAL,
    rarity: "common",
    icon: "⛏️",
    value: 10,
    weight: 1.0,
  },
  copper_ore: {
    id: "copper_ore",
    name: "Copper Ore",
    description: "Raw copper ore",
    type: ItemType.MATERIAL,
    rarity: "common",
    icon: "⛏️",
    value: 8,
    weight: 0.9,
  },
  gold_ring: {
    id: "gold_ring",
    name: "Gold Ring",
    description: "A valuable gold ring",
    type: ItemType.ACCESSORY,
    rarity: "rare",
    icon: "💍",
    value: 200,
    weight: 0.1,
    equipmentSlot: EquipmentSlot.RING_1,
    stats: { charisma: 2 },
  },
};

// ============================================================================
// ENEMIES
// ============================================================================

export const enemies: Record<string, Enemy> = {
  goblin: {
    id: "goblin",
    name: "Goblin",
    type: "humanoid",
    level: 1,
    stats: {
      maxHealth: 30,
      health: 30,
      maxMana: 10,
      mana: 10,
      strength: 8,
      intelligence: 6,
      dexterity: 10,
      constitution: 8,
      wisdom: 6,
      charisma: 5,
      armor: 2,
      magicResist: 1,
      critChance: 0.1,
      critDamage: 1.2,
      attackSpeed: 1.0,
      castSpeed: 0.8,
    },
    abilities: [abilities.slash],
    loot: [
      { item: items.iron_ore, chance: 0.3, quantity: 1 },
      { item: items.health_potion, chance: 0.2, quantity: 1 },
    ],
    experienceReward: 50,
    goldReward: 20,
    icon: "👹",
    description: "A small green humanoid creature",
    isBoss: false,
  },
  orc: {
    id: "orc",
    name: "Orc",
    type: "humanoid",
    level: 3,
    stats: {
      maxHealth: 60,
      health: 60,
      maxMana: 15,
      mana: 15,
      strength: 14,
      intelligence: 8,
      dexterity: 9,
      constitution: 13,
      wisdom: 8,
      charisma: 6,
      armor: 5,
      magicResist: 2,
      critChance: 0.12,
      critDamage: 1.3,
      attackSpeed: 0.95,
      castSpeed: 0.7,
    },
    abilities: [abilities.slash, abilities.power_strike],
    loot: [
      { item: items.iron_ore, chance: 0.5, quantity: 2 },
      { item: items.health_potion, chance: 0.4, quantity: 1 },
      { item: items.iron_sword, chance: 0.1, quantity: 1 },
    ],
    experienceReward: 120,
    goldReward: 50,
    icon: "🗡️",
    description: "A large green humanoid warrior",
    isBoss: false,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    type: "undead",
    level: 2,
    stats: {
      maxHealth: 40,
      health: 40,
      maxMana: 20,
      mana: 20,
      strength: 10,
      intelligence: 10,
      dexterity: 11,
      constitution: 9,
      wisdom: 7,
      charisma: 4,
      armor: 3,
      magicResist: 5,
      critChance: 0.15,
      critDamage: 1.4,
      attackSpeed: 1.1,
      castSpeed: 0.9,
    },
    abilities: [abilities.slash, abilities.backstab],
    loot: [
      { item: items.copper_ore, chance: 0.3, quantity: 1 },
      { item: items.health_potion, chance: 0.2, quantity: 1 },
    ],
    experienceReward: 80,
    goldReward: 35,
    icon: "💀",
    description: "An animated skeleton warrior",
    isBoss: false,
  },
  fire_elemental: {
    id: "fire_elemental",
    name: "Fire Elemental",
    type: "elemental",
    level: 4,
    stats: {
      maxHealth: 50,
      health: 50,
      maxMana: 60,
      mana: 60,
      strength: 9,
      intelligence: 15,
      dexterity: 12,
      constitution: 10,
      wisdom: 10,
      charisma: 8,
      armor: 2,
      magicResist: 15,
      critChance: 0.1,
      critDamage: 1.5,
      attackSpeed: 0.9,
      castSpeed: 1.2,
    },
    abilities: [abilities.fireball],
    loot: [
      { item: items.mana_potion, chance: 0.4, quantity: 1 },
      { item: items.health_potion, chance: 0.3, quantity: 1 },
    ],
    experienceReward: 150,
    goldReward: 60,
    icon: "🔥",
    description: "A creature made of pure fire",
    isBoss: false,
  },
  dragon: {
    id: "dragon",
    name: "Ancient Dragon",
    type: "dragon",
    level: 10,
    stats: {
      maxHealth: 300,
      health: 300,
      maxMana: 150,
      mana: 150,
      strength: 20,
      intelligence: 18,
      dexterity: 14,
      constitution: 20,
      wisdom: 16,
      charisma: 15,
      armor: 20,
      magicResist: 25,
      critChance: 0.2,
      critDamage: 2.0,
      attackSpeed: 1.1,
      castSpeed: 1.1,
    },
    abilities: [abilities.fireball, abilities.power_strike],
    loot: [
      { item: items.gold_ring, chance: 0.5, quantity: 1 },
      { item: items.mana_potion, chance: 0.8, quantity: 3 },
    ],
    experienceReward: 1000,
    goldReward: 500,
    icon: "🐉",
    description: "A legendary ancient dragon",
    isBoss: true,
    bossPhasesHealth: [200, 100],
  },
};

// ============================================================================
// QUESTS
// ============================================================================

export const quests: Record<string, Quest> = {
  goblin_slayer: {
    id: "goblin_slayer",
    title: "Goblin Slayer",
    description: "Defeat 5 goblins in the forest",
    giver: "npc_guard",
    status: QuestStatus.AVAILABLE,
    level: 1,
    objectives: [
      {
        id: "obj_1",
        type: QuestObjectiveType.DEFEAT_ENEMIES,
        description: "Defeat goblins",
        target: "goblin",
        progress: 0,
        required: 5,
        completed: false,
      },
    ],
    rewards: {
      experience: 200,
      gold: 100,
      items: [items.health_potion],
    },
    icon: "👹",
  },
  ore_collector: {
    id: "ore_collector",
    title: "Ore Collector",
    description: "Collect 10 iron ore",
    giver: "npc_blacksmith",
    status: QuestStatus.AVAILABLE,
    level: 2,
    objectives: [
      {
        id: "obj_1",
        type: QuestObjectiveType.COLLECT_ITEMS,
        description: "Collect iron ore",
        target: "iron_ore",
        progress: 0,
        required: 10,
        completed: false,
      },
    ],
    rewards: {
      experience: 150,
      gold: 150,
      items: [items.iron_sword],
    },
    icon: "⛏️",
  },
};

// ============================================================================
// CRAFTING RECIPES
// ============================================================================

export const recipes: Record<string, CraftingRecipe> = {
  steel_sword_recipe: {
    id: "steel_sword_recipe",
    name: "Craft Steel Sword",
    resultItem: items.steel_sword,
    materials: [
      { itemId: "iron_ore", quantity: 3 },
      { itemId: "copper_ore", quantity: 2 },
    ],
    level: 5,
    experience: 100,
  },
  iron_plate_recipe: {
    id: "iron_plate_recipe",
    name: "Craft Iron Plate",
    resultItem: items.iron_plate,
    materials: [
      { itemId: "iron_ore", quantity: 5 },
    ],
    level: 8,
    experience: 150,
  },
};

// ============================================================================
// ACHIEVEMENTS
// ============================================================================

export const achievements: Record<string, Achievement> = {
  first_victory: {
    id: "first_victory",
    name: "First Victory",
    description: "Win your first battle",
    type: AchievementType.COMBAT_VICTORY,
    icon: "🏆",
    progress: 0,
    requirement: 1,
    reward: { gold: 50, experience: 100 },
  },
  level_5: {
    id: "level_5",
    name: "Level 5",
    description: "Reach level 5",
    type: AchievementType.LEVEL_MILESTONE,
    icon: "⭐",
    progress: 0,
    requirement: 5,
    reward: { gold: 200, experience: 500 },
  },
  dragon_slayer: {
    id: "dragon_slayer",
    name: "Dragon Slayer",
    description: "Defeat the ancient dragon",
    type: AchievementType.BOSS_DEFEATED,
    icon: "🐉",
    progress: 0,
    requirement: 1,
    reward: { gold: 1000, experience: 2000 },
  },
};
