/**
 * Game database with all content: enemies, items, abilities, quests
 */

import {
  Ability,
  AbilityType,
  Achievement,
  CharacterClass,
  DamageType,
  Enemy,
  EquipmentSlot,
  Item,
  ItemType,
  Quest,
  StatusEffect,
} from "./game-types";

// ============ ABILITIES ============

export const abilities: Record<string, Ability> = {
  slash: {
    id: "slash",
    name: "Slash",
    description: "Basic physical attack",
    icon: "⚔️",
    type: AbilityType.ATTACK,
    damageType: DamageType.PHYSICAL,
    baseDamage: 15,
    manaCost: 0,
    cooldown: 0,
    levelRequired: 1,
    effects: [],
  },
  fireball: {
    id: "fireball",
    name: "Fireball",
    description: "Powerful fire spell",
    icon: "🔥",
    type: AbilityType.SPELL,
    damageType: DamageType.FIRE,
    baseDamage: 25,
    manaCost: 30,
    cooldown: 2,
    levelRequired: 3,
    classRequired: CharacterClass.MAGE,
    effects: [StatusEffect.BURN],
  },
  heal: {
    id: "heal",
    name: "Heal",
    description: "Restore health",
    icon: "💚",
    type: AbilityType.HEAL,
    damageType: DamageType.MAGICAL,
    baseDamage: 0,
    manaCost: 20,
    cooldown: 1,
    levelRequired: 2,
    effects: [],
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    description: "High crit attack",
    icon: "🗡️",
    type: AbilityType.ATTACK,
    damageType: DamageType.PHYSICAL,
    baseDamage: 20,
    manaCost: 0,
    cooldown: 1,
    levelRequired: 1,
    classRequired: CharacterClass.ROGUE,
    effects: [],
  },
  shield_bash: {
    id: "shield_bash",
    name: "Shield Bash",
    description: "Stun enemy",
    icon: "🛡️",
    type: AbilityType.ATTACK,
    damageType: DamageType.PHYSICAL,
    baseDamage: 12,
    manaCost: 15,
    cooldown: 2,
    levelRequired: 2,
    classRequired: CharacterClass.PALADIN,
    effects: [StatusEffect.STUN],
  },
  poison_dart: {
    id: "poison_dart",
    name: "Poison Dart",
    description: "Poison attack",
    icon: "🎯",
    type: AbilityType.ATTACK,
    damageType: DamageType.PHYSICAL,
    baseDamage: 10,
    manaCost: 10,
    cooldown: 1,
    levelRequired: 2,
    classRequired: CharacterClass.ROGUE,
    effects: [StatusEffect.POISON],
  },
  ice_spike: {
    id: "ice_spike",
    name: "Ice Spike",
    description: "Freeze enemy",
    icon: "❄️",
    type: AbilityType.SPELL,
    damageType: DamageType.COLD,
    baseDamage: 18,
    manaCost: 25,
    cooldown: 2,
    levelRequired: 3,
    classRequired: CharacterClass.MAGE,
    effects: [StatusEffect.FREEZE],
  },
  power_strike: {
    id: "power_strike",
    name: "Power Strike",
    description: "Massive attack",
    icon: "💥",
    type: AbilityType.ATTACK,
    damageType: DamageType.PHYSICAL,
    baseDamage: 30,
    manaCost: 0,
    cooldown: 3,
    levelRequired: 5,
    classRequired: CharacterClass.WARRIOR,
    effects: [],
  },
  lightning_bolt: {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    description: "Electric attack",
    icon: "⚡",
    type: AbilityType.SPELL,
    damageType: DamageType.LIGHTNING,
    baseDamage: 22,
    manaCost: 28,
    cooldown: 2,
    levelRequired: 4,
    classRequired: CharacterClass.MAGE,
    effects: [],
  },
};

// ============ ITEMS ============

export const items: Record<string, Item> = {
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    description: "A basic iron sword",
    icon: "🗡️",
    type: ItemType.WEAPON,
    rarity: "common",
    value: 50,
    slot: EquipmentSlot.MAIN_HAND,
    statBonus: { strength: 3 },
  },
  leather_armor: {
    id: "leather_armor",
    name: "Leather Armor",
    description: "Light protective gear",
    icon: "🧥",
    type: ItemType.ARMOR,
    rarity: "common",
    value: 40,
    slot: EquipmentSlot.CHEST,
    statBonus: { armor: 5 },
  },
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    description: "Restore 50 health",
    icon: "🧪",
    type: ItemType.CONSUMABLE,
    rarity: "common",
    value: 20,
  },
  mana_potion: {
    id: "mana_potion",
    name: "Mana Potion",
    description: "Restore 30 mana",
    icon: "💙",
    type: ItemType.CONSUMABLE,
    rarity: "common",
    value: 25,
  },
  steel_sword: {
    id: "steel_sword",
    name: "Steel Sword",
    description: "A well-crafted steel sword",
    icon: "⚔️",
    type: ItemType.WEAPON,
    rarity: "uncommon",
    value: 100,
    slot: EquipmentSlot.MAIN_HAND,
    statBonus: { strength: 6 },
  },
  iron_helmet: {
    id: "iron_helmet",
    name: "Iron Helmet",
    description: "Protects your head",
    icon: "⛑️",
    type: ItemType.ARMOR,
    rarity: "common",
    value: 35,
    slot: EquipmentSlot.HEAD,
    statBonus: { armor: 3 },
  },
  gold_ring: {
    id: "gold_ring",
    name: "Gold Ring",
    description: "Increases intelligence",
    icon: "💍",
    type: ItemType.ACCESSORY,
    rarity: "uncommon",
    value: 60,
    slot: EquipmentSlot.RING_1,
    statBonus: { intelligence: 4 },
  },
  cloth_robe: {
    id: "cloth_robe",
    name: "Cloth Robe",
    description: "Mage's attire",
    icon: "👗",
    type: ItemType.ARMOR,
    rarity: "common",
    value: 45,
    slot: EquipmentSlot.CHEST,
    statBonus: { intelligence: 3, magicResist: 2 },
  },
  copper_ore: {
    id: "copper_ore",
    name: "Copper Ore",
    description: "Crafting material",
    icon: "⛏️",
    type: ItemType.MATERIAL,
    rarity: "common",
    value: 10,
  },
  iron_ore: {
    id: "iron_ore",
    name: "Iron Ore",
    description: "Crafting material",
    icon: "🪨",
    type: ItemType.MATERIAL,
    rarity: "uncommon",
    value: 20,
  },
};

// ============ ENEMIES ============

export const enemies: Record<string, Enemy> = {
  goblin: {
    id: "goblin",
    name: "Goblin",
    level: 1,
    type: "humanoid",
    stats: {
      health: 30,
      maxHealth: 30,
      mana: 10,
      maxMana: 10,
      strength: 6,
      intelligence: 3,
      dexterity: 7,
      constitution: 5,
      wisdom: 4,
      charisma: 2,
      armor: 2,
      magicResist: 1,
      critChance: 0.1,
      critDamage: 1.3,
    },
    abilities: [abilities.slash],
    loot: [
      { item: items.copper_ore, chance: 0.5 },
      { item: items.health_potion, chance: 0.3 },
    ],
    experienceReward: 50,
    goldReward: 25,
    isBoss: false,
  },
  orc: {
    id: "orc",
    name: "Orc",
    level: 2,
    type: "humanoid",
    stats: {
      health: 50,
      maxHealth: 50,
      mana: 15,
      maxMana: 15,
      strength: 9,
      intelligence: 4,
      dexterity: 5,
      constitution: 8,
      wisdom: 5,
      charisma: 3,
      armor: 4,
      magicResist: 2,
      critChance: 0.12,
      critDamage: 1.4,
    },
    abilities: [abilities.slash, abilities.shield_bash],
    loot: [
      { item: items.iron_ore, chance: 0.4 },
      { item: items.health_potion, chance: 0.5 },
    ],
    experienceReward: 100,
    goldReward: 50,
    isBoss: false,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    level: 2,
    type: "undead",
    stats: {
      health: 40,
      maxHealth: 40,
      mana: 20,
      maxMana: 20,
      strength: 7,
      intelligence: 6,
      dexterity: 8,
      constitution: 4,
      wisdom: 3,
      charisma: 1,
      armor: 3,
      magicResist: 3,
      critChance: 0.15,
      critDamage: 1.5,
    },
    abilities: [abilities.slash, abilities.poison_dart],
    loot: [
      { item: items.iron_ore, chance: 0.3 },
      { item: items.mana_potion, chance: 0.4 },
    ],
    experienceReward: 90,
    goldReward: 40,
    isBoss: false,
  },
  troll: {
    id: "troll",
    name: "Troll",
    level: 3,
    type: "humanoid",
    stats: {
      health: 80,
      maxHealth: 80,
      mana: 20,
      maxMana: 20,
      strength: 11,
      intelligence: 3,
      dexterity: 4,
      constitution: 12,
      wisdom: 4,
      charisma: 2,
      armor: 6,
      magicResist: 2,
      critChance: 0.08,
      critDamage: 1.3,
    },
    abilities: [abilities.slash, abilities.power_strike],
    loot: [
      { item: items.iron_ore, chance: 0.6 },
      { item: items.health_potion, chance: 0.5 },
    ],
    experienceReward: 150,
    goldReward: 75,
    isBoss: false,
  },
  fire_elemental: {
    id: "fire_elemental",
    name: "Fire Elemental",
    level: 4,
    type: "elemental",
    stats: {
      health: 60,
      maxHealth: 60,
      mana: 50,
      maxMana: 50,
      strength: 5,
      intelligence: 10,
      dexterity: 6,
      constitution: 6,
      wisdom: 7,
      charisma: 4,
      armor: 2,
      magicResist: 8,
      critChance: 0.1,
      critDamage: 1.4,
    },
    abilities: [abilities.fireball, abilities.slash],
    loot: [
      { item: items.mana_potion, chance: 0.7 },
      { item: items.gold_ring, chance: 0.2 },
    ],
    experienceReward: 200,
    goldReward: 100,
    isBoss: false,
  },
};

// ============ QUESTS ============

export const quests: Record<string, Quest> = {
  goblin_slayer: {
    id: "goblin_slayer",
    title: "Goblin Slayer",
    description: "Defeat 5 goblins in the forest",
    objectives: [
      {
        id: "kill_goblins",
        description: "Defeat goblins",
        target: 5,
        current: 0,
      },
    ],
    rewards: {
      experience: 200,
      gold: 100,
      items: [items.iron_sword],
    },
    level: 1,
    completed: false,
  },
  orc_hunt: {
    id: "orc_hunt",
    title: "Orc Hunt",
    description: "Defeat 3 orcs in the mountains",
    objectives: [
      {
        id: "kill_orcs",
        description: "Defeat orcs",
        target: 3,
        current: 0,
      },
    ],
    rewards: {
      experience: 300,
      gold: 150,
      items: [items.steel_sword],
    },
    level: 2,
    completed: false,
  },
};

// ============ ACHIEVEMENTS ============

export const achievements: Record<string, Achievement> = {
  first_kill: {
    id: "first_kill",
    name: "First Blood",
    description: "Defeat your first enemy",
    icon: "⚔️",
    unlocked: false,
  },
  level_5: {
    id: "level_5",
    name: "Rising Star",
    description: "Reach level 5",
    icon: "⭐",
    unlocked: false,
  },
  level_10: {
    id: "level_10",
    name: "Legendary",
    description: "Reach level 10",
    icon: "👑",
    unlocked: false,
  },
  rich: {
    id: "rich",
    name: "Wealthy",
    description: "Accumulate 1000 gold",
    icon: "💰",
    unlocked: false,
  },
  collector: {
    id: "collector",
    name: "Collector",
    description: "Collect 10 different items",
    icon: "🎁",
    unlocked: false,
  },
};

// ============ CHARACTER TEMPLATES ============

export const characterTemplates = {
  warrior: {
    class: CharacterClass.WARRIOR,
    stats: {
      health: 120,
      maxHealth: 120,
      mana: 30,
      maxMana: 30,
      strength: 12,
      intelligence: 4,
      dexterity: 6,
      constitution: 14,
      wisdom: 6,
      charisma: 5,
      armor: 8,
      magicResist: 2,
      critChance: 0.1,
      critDamage: 1.4,
    },
    startingAbilities: [abilities.slash, abilities.shield_bash, abilities.power_strike],
  },
  mage: {
    class: CharacterClass.MAGE,
    stats: {
      health: 70,
      maxHealth: 70,
      mana: 80,
      maxMana: 80,
      strength: 4,
      intelligence: 14,
      dexterity: 7,
      constitution: 6,
      wisdom: 10,
      charisma: 6,
      armor: 2,
      magicResist: 6,
      critChance: 0.08,
      critDamage: 1.5,
    },
    startingAbilities: [abilities.fireball, abilities.ice_spike, abilities.lightning_bolt],
  },
  rogue: {
    class: CharacterClass.ROGUE,
    stats: {
      health: 80,
      maxHealth: 80,
      mana: 40,
      maxMana: 40,
      strength: 8,
      intelligence: 6,
      dexterity: 14,
      constitution: 7,
      wisdom: 5,
      charisma: 7,
      armor: 4,
      magicResist: 3,
      critChance: 0.25,
      critDamage: 1.8,
    },
    startingAbilities: [abilities.backstab, abilities.poison_dart, abilities.slash],
  },
  paladin: {
    class: CharacterClass.PALADIN,
    stats: {
      health: 100,
      maxHealth: 100,
      mana: 50,
      maxMana: 50,
      strength: 10,
      intelligence: 7,
      dexterity: 7,
      constitution: 11,
      wisdom: 9,
      charisma: 9,
      armor: 6,
      magicResist: 4,
      critChance: 0.12,
      critDamage: 1.5,
    },
    startingAbilities: [abilities.slash, abilities.shield_bash, abilities.heal],
  },
};
